employee/urls.py
from django.urls import path
from django.views.generic import TemplateView
from employee.views import (empviewset,
                            uploadfile,
                            empeditviewset,
                            delete_emp)

app_name = "employees"
urlpatterns = [
    path('upload_files/',TemplateView.as_view(template_name='upload-data.html'),name='upload_files'),
    path('view_employee/',empviewset,name='view_employee'),
    path('edit_employee/<pk>',empeditviewset,name='edit_employee'),
    path('delete_employee/<pk>',delete_emp,name='delete_employee'),
    path('file_data/',uploadfile,name='file_data')
]

entity_users/urls.py
from django.urls import path
from entity_users.views import homeviewset,clientviewset1
app_name = "entity_users"
urlpatterns = [
    path('client_welcome/',homeviewset,name='client_welcome'),
    path('client_user1/',clientviewset1,name='client_user1'),
]

surveyqa/urls.py


from django.urls import path
from surveyqa.views import questions,questionviewset,editsurveyqa,questiondelete,sendsms
app_name = "surveyqas"
urlpatterns = [
    path('add_questions/',questionviewset,name='add_questions'),
    path('edit_surveyqa/<pk>',editsurveyqa,name='edit_surveyqa'),
    path('survey_qa',questions,name='survey_qa'),
    path('deleteqa/<pk>',questiondelete,name='deleteqa'),
    path('sendsms/',sendsms,name='sendsms')
]

walnuteq/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import validate_login,log_out_user,forgot_password,download_sample
from twilio_app.views import inbound_sms
urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout_users/',log_out_user,name='logout_admin'),
    path('forgot_password/',forgot_password,name="forgot_password"),
    path('',validate_login,name='validate'),
    path('employees/',include('employee.urls')),
    path('entity_users/',include('entity_users.urls')),
    path('surveyqas/',include('surveyqa.urls')),
    path('download_sample',download_sample,name='download_sample'),
    path('sms',inbound_sms),
]

#Configure Admin Title and Header

admin.site.site_header = "WALNUT EQ"
admin.site.site_title = "walnut eq"

employee/models.py
import uuid
from entity_users.models import EntityUsers
from django.db import models
from django.db.models import Q
from django.contrib.auth.hashers import make_password
import pandas as pd
import random,string,os
from django.core.exceptions import ValidationError
# Create your models here.

class Employee(models.Model):
    id = models.UUIDField(default=uuid.uuid4,unique=True,editable=False,primary_key=True)
    company = models.ForeignKey(EntityUsers, related_name='emp_entityusers',on_delete=models.CASCADE)
    first_name = models.CharField(max_length=225)
    middle_name = models.CharField(max_length=225,blank=True,null=True)
    last_name = models.CharField(max_length=225)
    phone_number = models.BigIntegerField(unique=True)
    email = models.CharField(unique=True,max_length=225)
    temp_password = models.CharField(max_length=225,blank=True,null=True)
    password = models.CharField(max_length=225,blank=True,null=True)
    department = models.CharField(max_length=225,blank=True,null=True)
    job_title = models.CharField(max_length=225,blank=True,null=True)
    region = models.CharField(max_length=225,blank=True,null=True)
    language = models.CharField(max_length=225,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.email)
    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'
    def clean(self):
        password1 = "".join(
            random.choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=6))
        temp_password = make_password(password1)
        self.temp_password = temp_password

class UploadEmployeeFile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    file_name = models.FileField(upload_to='')
    company = models.ForeignKey(EntityUsers,related_name='upload_entityusers',on_delete=models.CASCADE,null=True)

    class Meta:
        verbose_name = "UploadEmployeeFile"

    def clean(self):
        file_name1 = str(self.file_name)
        entity_user_id = self.company.id
        path, extension = os.path.splitext(file_name1)
        if extension in [".csv", ".xlsx"]:
            try:
                if extension == '.xlsx':
                    df_group = pd.read_excel(file_name1)
                else:
                    df_group = pd.read_csv(file_name1)
                file_cloumns = set(df_group.columns)
                required_columns = {"email","phone_number"}
                if not required_columns.issubset(file_cloumns):
                    raise ValidationError("Required (email or phone_number) fields missing")
                duplicate_email = df_group.duplicated('email').sum()
                if duplicate_email > 0:
                    raise ValidationError("email should be unique")
                duplicate_phone = df_group.duplicated('phone_number').sum()
                if duplicate_phone > 0:
                    raise ValidationError("phone number should be unique")
                db_check_email = df_group["email"].to_list()
                db_check_phone = df_group["phone_number"].to_list()
                if Employee.objects.filter(Q(email__in=db_check_email) | Q(phone_number__in=db_check_phone)).exists():
                    raise ValidationError("required (email,phone_number) filed values alrady exists")
                df_group = df_group.drop_duplicates(["phone_number", "email"], keep='last', ignore_index=True)
                obj_dict = df_group.to_dict(orient='records')
                password1 = "".join(
                    random.choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=6))
                temp_password = make_password(password1)
                from entity_users.models import EntityUsers
                bulk_list = []
                for obj_dic in obj_dict:
                    Employee(
                        first_name=obj_dic.get("first_name"),
                        last_name=obj_dic.get("last_name"),
                        middle_name=obj_dic.get("last_name"),
                        email=obj_dic.get("email"),
                        phone_number=obj_dic.get("phone_number"),
                        job_title=obj_dic.get("job_title"),
                        language=obj_dic.get("language"),
                        department=obj_dic.get("department"),
                        region=obj_dic.get("region"),
                        company_id=entity_user_id,
                        temp_password=temp_password

                    ).save()
            except Exception as e:
                raise ValidationError("file error due to {}".format(e))
        else:
            raise ValidationError("file format is must be csv")

employee/views.py
import random,string

from django.contrib.auth.hashers import make_password
from django.shortcuts import render, HttpResponse, redirect
from .models import UploadEmployeeFile,Employee
from entity_users.models import EntityUsers
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
import os
import pandas as pd
from django.contrib import messages
from django.core.validators import validate_email
# Create your views here.
# @login_required(login_url="login_users")
def empviewset(request):
    session_email = request.session.get("email")
    if session_email:
        entity = EntityUsers.objects.get(email=session_email)
        parent_data = EntityUsers.objects.filter(parent_entityuser=entity)
        emp_data = Employee.objects.filter(company__company=entity.company)
        payload = request.GET
        if payload.get('search'):
            emp_data = emp_data.filter(
                Q(first_name__iexact=payload.get('search')) | Q(last_name__iexact=payload.get("search")))
        # if parent_data:
        #     emp_data.filter(company__parent_entityuser=parent_data).distinct()
        if emp_data:
            emp_data = emp_data.order_by("created_at")
            paginator = Paginator(emp_data, 5)
            try:
                page = int(request.GET.get('page', '1'))
            except:
                page = 1
            try:
                emp_data = paginator.page(page)
            except:
                emp_data = paginator.page(page)
            return render(request, 'employee.html', {"emp_data": emp_data})
        else:
            return render(request, 'employee.html', {"emp_data": emp_data})
    else:
        return render(request, 'login.html')

def empeditviewset(request,pk):
    session_email = request.session.get("email")
    if session_email:
        entity = EntityUsers.objects.get(email=session_email)
        try:
            emp_data = Employee.objects.get(pk=pk)
        except Exception as e:
            messages.error(request, f"Employee details falied to upate due to{e}")
            return render(request, "edit-employee.html")
        if request.method == "POST":
            payload = request.POST
            if payload.get("email") != emp_data.email:
                try:
                    validate_email(payload.get("email"))
                except Exception as e:
                    messages.error(request, f"This email {payload.get('email')} not a valid one")
                    return render(request, "edit-employee.html", context={'emp_data': emp_data})
                if Employee.objects.filter(email=payload.get('email')).exists():
                    messages.error(request, f"This email {payload.get('email')} is already exists")
                    return render(request, "edit-employee.html",context={'emp_data':emp_data})
            if int(payload.get("phone")) != emp_data.phone_number:
                if Employee.objects.filter(phone_number=payload.get('phone')).exists():
                    messages.error(request, f"This phone {payload.get('phone')} is already exists")
                    return render(request, "edit-employee.html",{'emp_data':emp_data})
            try:
                emp_data.first_name = payload.get('first_name', emp_data.first_name)
                emp_data.last_name = payload.get('last_name', emp_data.last_name)
                emp_data.middle_name = payload.get('middle_name', emp_data.middle_name)
                emp_data.email = payload.get('email', emp_data.email)
                emp_data.phone_number = int(payload.get('phone'))
                emp_data.job_title = payload.get("job_title")
                emp_data.language = payload.get("language")
                emp_data.department = payload.get("department")
                emp_data.region = payload.get("region")
                emp_data.save()
                messages.success(request, 'emp details updated')
                return redirect("employees:view_employee")
            except Exception as e:
                messages.error(request, f"failed to save data in db due to {e}")
                return render(request, "edit-employee.html", {'emp_data': emp_data})
        else:
            return render(request,"edit-employee.html",context={'emp_data':emp_data})

    else:
        return render(request,'login.html')

def delete_emp(request,pk):
    session_email = request.session.get("email")
    try:
        emp_data = Employee.objects.get(pk=pk)
        emp_data.delete()
        messages.success(request, 'emp details deleted')
        return redirect("employees:view_employee")
    except Exception as e:
        messages.error(request, f"Employee details falied to upate due to{e}")
        return render(request, "edit-employee.html")


# @login_required(login_url="login_users")
def uploadfile(request):
    if request.method == "POST":
        try:
            file_name = request.FILES['file']
            session_email = request.session.get("email")
            file_name1= str(file_name)
            path,extension = os.path.splitext(file_name1)
            if extension in [".csv",".xlsx"]:
                try:
                    if extension == '.xlsx':
                        df_group = pd.read_excel(file_name)
                    else:
                        df_group = pd.read_csv(file_name)
                    file_cloumns = set(df_group.columns)
                    required_columns = {"email", "phone_number"}
                    if not required_columns.issubset(file_cloumns):
                        messages.error(request,'Required (email or phone_number) fields missing')
                        return render(request,"upload-data.html")
                    duplicate_email = df_group.duplicated('email').sum()
                    if duplicate_email > 0:
                        messages.error(request,"email should be unique")
                        return render(request,"upload-data.html")
                    duplicate_phone = df_group.duplicated('phone_number').sum()
                    if duplicate_phone > 0:
                        messages.error(request,'phone number should be unique')
                        return render(request,"upload-data.html")
                    db_check_email = df_group["email"].to_list()
                    db_check_phone =  df_group["phone_number"].to_list()
                    if Employee.objects.filter(Q(email__in=db_check_email) | Q(phone_number__in=db_check_phone)).exists():
                        messages.error(request,'required (email,phone_number) filed values alrady exists')
                        return render(request,"upload-data.html")
                    df_group =df_group.drop_duplicates(["phone_number","email"],keep='last',ignore_index=True)
                    obj_dict = df_group.to_dict(orient='records')
                    password1 = "".join(
                        random.choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=6))
                    temp_password = make_password(password1)
                    from entity_users.models import EntityUsers
                    entity = EntityUsers.objects.get(email=session_email)
                    bulk_list = []
                    for obj_dic in obj_dict:
                        Employee(
                                first_name = obj_dic.get("first_name"),
                                last_name = obj_dic.get("last_name"),
                                middle_name = obj_dic.get("last_name"),
                                email = obj_dic.get("email"),
                                phone_number = obj_dic.get("phone_number"),
                                job_title=obj_dic.get("job_title"),
                                language=obj_dic.get("language"),
                                department=obj_dic.get("department"),
                                region=obj_dic.get("region"),
                                company= entity,
                                temp_password = temp_password,
                                password = temp_password

                        ).save()
                        messages.success(request,'data saved.')
                    return render(request,"upload-data.html")
                except Exception as e:
                    messages.error(request,"file error due to {}".format(e))
                    return render(request,"upload-data.html")
            else:
                messages.error(request,'file format must be .csv')
                return render(request, "upload-data.html")
        except Exception as e:
            messages.error(request, f'file upload failed due to {e}')
            return render(request, "upload-data.html")
    else:
        return render(request, "upload-data.html")

templates/base.html
{% load static %}
<head>
    {% include 'includes/head.html' %}
</head>
<header class="head-wrap">
    <nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-2 menu-tab">
                    <button class="btn menu-btn" id="sidebarOpen" onclick="showMenu()">
                        <i class="fa-solid fa-bars"></i>
                    </button>
                </div>
                <div class="col-5 col-md-8">
                    <h1 class="nav-title">Dashboard</h1>
                </div>
                <div class="col-5 col-md-4 pd-lft">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{request.session.email}}
                            <img src="{%static 'images/user.png'%}" alt="user logo" />
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li>
                                <a class="dropdown-item" href="#">
                                    <i class="fa-solid fa-gear"></i>
                                    Settings</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{%url 'logout_admin'%}">
                                    <i class="fa-solid fa-right-from-bracket"></i>
                                    Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="side-card menu-trans" id="sidebar-wrapper">
    <!-- <button class="btn menu-btn" onclick="closeMenu()">
        <i class="fa-solid fa-xmark"></i>
    </button> -->
    <div class="side-icon">
        <img class="s-logo" src="{%static 'images/SidebarLogo.png'%}" alt="logo" />
    </div>
    <div class="list-group">
        {%block sidebar%}
        <a class="list-item list-action" href="{% url 'entity_users:client_welcome' %}">Home</a>
        {% if request.session.parent_user == None %}
        <a class="list-item list-action" href="{% url 'entity_users:client_user1' %}">Add User</a>
        {% endif %}
         <a class="list-item list-action" href="{% url 'employees:view_employee' %}">Employees</a>
<!--        <a class="list-item list-action" href="{% url 'employees:upload_files' %}">Upload Data</a>-->
        <a class="list-item list-action" href="{% url 'surveyqas:survey_qa' %}">Survey QA</a>
        <a class="list-item list-action" href="{% url 'surveyqas:sendsms' %}">Quick Send</a>
        <a class="list-item list-action" href="#!">Schedule SMS</a>
        {%endblock%}
    </div>
</div>
{% include 'includes/messages.html' %}
{% block content %}
{% endblock %}

templates/employee.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block content%}
<html lang="en">
<head>

</head>

<body>
    <div class="page-wrap">
        <!-- Sidebar -->
        <div id="sidebar-container"></div>

        <div id="page-content-wrap" class="home-wrap">
            <!-- Header -->
            <div id="header"></div>

            <!-- Main page content -->
            <div class="main-wrap">
                <!-- <div class="top-btn">
                    <button class="btn back-btn">
                        <i class="fa-solid fa-arrow-left"></i>
                        Back
                    </button>
                </div> -->
                <div class="container-fluid">
                    <div class="col-12 col-xl-11">
                        <div>
                            <div class="d-flex justify-content-between">
                                <div class="search-box">
                                    <form method="get" action="{% url 'employees:view_employee' %}">
                                        <input type="text" class="form-control" placeholder="Search User by First name or Last name" name="search">
                                        <button class="btn"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                                <div>
                                    <a class="btn btn-primary lt-2" href="{% url 'employees:upload_files' %}">Upload Data</a>
                                </div>
                            </div>
                            {% if emp_data %}
                            <div class="card emp-table">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">First name</th>
                                                <th scope="col">Last name</th>
                                                <th scope="col">Email</th>
                                                <th scope="col">Phone number</th>
                                                <th scope="col">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for i in emp_data %}
                                            <tr>
                                                <td>{{i.first_name}}</td>
                                                <td>{{i.last_name}}</td>
                                                <td>{{i.email}}</td>
                                                <td>{{i.phone_number}}</td>
                                                <td>
                                                    <div class="icon-box">
                                                        <a href="{% url 'employees:edit_employee' i.id %}"><i
                                                                class="fa-solid fa-pen-to-square edit"></i></a>
                                                        <a href="{% url 'employees:delete_employee' i.id %}" class="curs-point" data-bs-toggle="modal" data-bs-target="#deleteBackdrop" id="deleteButton{{i.id}}"><i
                                                                class="fa-solid fa-trash-can del"></i></a>
                                                        {% include 'modal/link_emp_deleted_modal.html' %}
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% endif %}
                            <div class="page-box">
                                <nav aria-label="...">
                                {% if emp_data.has_other_pages %}
                                <ul class="pagination">
                                  {% if emp_data.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link arrow" href="?page={{ emp_data.previous_page_number }}" aria-label="Previous">
                                                <i class="fa-solid fa-angle-left"></i>
                                  {% else %}
                                    <li class="page-item disabled"  aria-label="Previous"></li>
                                  {% endif %}

                                  {% for i in emp_data.paginator.page_range %}
                                    {% if emp_data.number == i %}
                                    <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                  {% endfor %}

                                  {% if emp_data.has_next %}
                                    <li class="page-item">
                                        <a class="page-link arrow" href="?page={{ emp_data.next_page_number }}" aria-label="Next">
                                            <i class="fa-solid fa-angle-right"></i>
                                        </a></li>
                                  {% else %}
                                    <li class="page-item disabled" aria-label="Next"></li>
                                  {% endif %}
                                </ul>
                              {% endif %}
                              </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Script -->
    </div>
</body>

</html>
{% endblock %}

templates/logout.html

<table align="right">
    <tr><th><a href="{% url 'logout_admin' %}">logout</a> </th></tr>
</table>
{% block content %}
{% endblock %}

templates/superadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'logout.html' %}
{% block content %}
<a href="{%url 'upload_files'%}">upload_files</a><br>
<a href="{%url 'view_employee'%}">list_employee</a><br>
<a href="{%url 'client_users'%}">client_users</a>
{% endblock %}
</body>
</html>

templates/survey-qa.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block content%}
<html lang="en">

<head>

</head>

<body>
    <div class="page-wrap">
        <!-- Sidebar -->
        <div id="sidebar-container"></div>

        <div id="page-content-wrap" class="home-wrap">
            <!-- Header -->
            <div id="header"></div>

            <!-- Main page content -->
            <div class="main-wrap">
                <!-- <div class="top-btn">
                    <button class="btn back-btn">
                        <i class="fa-solid fa-arrow-left"></i>
                        Back
                    </button>
                </div> -->
                <div class="container-fluid">
                    <div class="col-12 col-xl-11">
                        <div>
                            <div class="d-flex justify-content-end">
                                <div>
                                    <a class="btn btn-primary lt-2" href="{% url 'surveyqas:add_questions' %}">Add Questions</a>
                                </div>
                            </div>
                            {% if question_obj %}
                            <div class="card qa-table">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">Questions</th>
                                                <th scope="col">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in question_obj %}
                                            <tr>
                                                <td>{{ i.name }}</td>
                                                <td>
                                                    <div class="icon-box">
                                                        <a href="{% url 'surveyqas:edit_surveyqa' i.id %}">
                                                            <i class="fa-solid fa-pen-to-square edit"></i></a>
                                                        <a href="{% url 'surveyqas:deleteqa' i.id %}" class="curs-point" data-bs-toggle="modal" data-bs-target="#deleteBackdrop" id="deleteButton{{i.id}}"><i
                                                                class="fa-solid fa-trash-can del"></i></a>
                                                        {% include 'modal/link_emp_deleted_modal.html' %}
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% endif %}
                            <div class="page-box">
                                <nav aria-label="Page navigation">
                                    {% if question_obj.has_other_pages %}
                                <ul class="pagination">
                                  {% if question_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link arrow" href="?page={{ question_obj.previous_page_number }}" aria-label="Previous">
                                                <i class="fa-solid fa-angle-left"></i>
                                  {% else %}
                                    <li class="page-item disabled"  aria-label="Previous"></li>
                                  {% endif %}

                                  {% for i in question_obj.paginator.page_range %}
                                    {% if question_obj.number == i %}
                                    <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                  {% endfor %}

                                  {% if question_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link arrow" href="?page={{ question_obj.next_page_number }}" aria-label="Next">
                                            <i class="fa-solid fa-angle-right"></i>
                                        </a></li>
                                  {% else %}
                                    <li class="page-item disabled" aria-label="Next"></li>
                                  {% endif %}
                                </ul>
                              {% endif %}
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>

</html>
{% endblock %}